[2018-10-04 21:19:22 +0700] [7965] [INFO] Starting gunicorn 19.9.0
[2018-10-04 21:19:22 +0700] [7965] [INFO] Listening at: http://0.0.0.0:6000 (7965)
[2018-10-04 21:19:22 +0700] [7965] [INFO] Using worker: sync
[2018-10-04 21:19:22 +0700] [7968] [INFO] Booting worker with pid: 7968
[2018-10-04 21:19:22 +0700] [7968] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'wsgi'
[2018-10-04 21:19:22 +0700] [7968] [INFO] Worker exiting (pid: 7968)
[2018-10-04 21:19:22 +0700] [7965] [INFO] Shutting down: Master
[2018-10-04 21:19:22 +0700] [7965] [INFO] Reason: Worker failed to boot.
[2018-10-04 21:19:27 +0700] [7988] [INFO] Starting gunicorn 19.9.0
[2018-10-04 21:19:27 +0700] [7988] [INFO] Listening at: http://0.0.0.0:6000 (7988)
[2018-10-04 21:19:27 +0700] [7988] [INFO] Using worker: sync
[2018-10-04 21:19:27 +0700] [7992] [INFO] Booting worker with pid: 7992
[2018-10-04 21:19:27 +0700] [7992] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'wsgi'
[2018-10-04 21:19:27 +0700] [7992] [INFO] Worker exiting (pid: 7992)
[2018-10-04 21:19:27 +0700] [7988] [INFO] Shutting down: Master
[2018-10-04 21:19:27 +0700] [7988] [INFO] Reason: Worker failed to boot.
[2018-10-04 21:19:31 +0700] [7998] [INFO] Starting gunicorn 19.9.0
[2018-10-04 21:19:31 +0700] [7998] [INFO] Listening at: http://0.0.0.0:6000 (7998)
[2018-10-04 21:19:31 +0700] [7998] [INFO] Using worker: sync
[2018-10-04 21:19:31 +0700] [8001] [INFO] Booting worker with pid: 8001
[2018-10-04 21:19:31 +0700] [8001] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/eng-alson/anaconda3/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ModuleNotFoundError: No module named 'wsgi'
[2018-10-04 21:19:31 +0700] [8001] [INFO] Worker exiting (pid: 8001)
[2018-10-04 21:19:31 +0700] [7998] [INFO] Shutting down: Master
[2018-10-04 21:19:31 +0700] [7998] [INFO] Reason: Worker failed to boot.
